### ISSUE TITLE
请问您之前尝试过用这个工具交叉编译吗？成功了吗？为什么我最终生成的不是一个可执行文件？

### ISSUE THREAD

**Issue by yuzu-ogura** [genIoco/gcc-vxworks#1]

**Comment by genIoco** [comment]
是的成功了，生成后的文件类型vxworks的可执行文件，在vxworks中可使用`ld`命令加载程序，并运行`main`主函数，如下图
![image](https://github.com/genIoco/gcc-vxworks/assets/49811656/db159193-e39f-4613-a01e-bc43a2004599)

**Comment by yuzu-ogura** [comment]
> 是的成功了，生成后的文件类型vxworks的可执行文件，在vxworks中可使用`ld`命令加载程序，并运行`main`主函数，如下图 ![image](https://private-user-images.githubusercontent.com/49811656/320396508-db159193-e39f-4613-a01e-bc43a2004599.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NjI5OTIsIm5iZiI6MTcxMjU2MjY5MiwicGF0aCI6Ii80OTgxMTY1Ni8zMjAzOTY1MDgtZGIxNTkxOTMtZTM5Zi00NjEzLWEwMWUtYmM0M2EyMDA0NTk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDA3NTEzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4M2U3OGE2N2NlYWJlNjY0ZmUyMjc4ZjY1YzUyNGFiYjQ0NTM0YTQ1NGJjYmI2ZDM5Mzc4MzBkZDQ5ZDg2YmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Dqc3W0zfeFznfI4r6Bukwqb1tB2VsXgsS17avyUS3zI)


谢谢您的回复，可以帮我看一下，是哪里出现错误了吗？
这是我的vxworks版本：
![image](https://github.com/genIoco/gcc-vxworks/assets/166282486/69e21a21-20dc-4706-9aef-bb2157678771)

我在windows上编译的，我的文件列表是这样的
![image](https://github.com/genIoco/gcc-vxworks/assets/166282486/7ed8475d-5fba-4acf-baac-2ea97df0be90)
然后main.cpp是这样的
![image](https://github.com/genIoco/gcc-vxworks/assets/166282486/8bed4bfc-17bc-4007-af70-0e30814c0c98)
CMakeLists.txt是这样的
![image](https://github.com/genIoco/gcc-vxworks/assets/166282486/f3cf944e-d724-42ca-b784-981338e09203)
接下来执行编译cmake：
![image](https://github.com/genIoco/gcc-vxworks/assets/166282486/339e8587-8fcc-4de7-80bc-3f06f7802514)
然后是构建ninja：
![image](https://github.com/genIoco/gcc-vxworks/assets/166282486/f162b660-8d28-4e19-b8fa-1f5b389a1c58)
最终加载文件时候出错了：
![image](https://github.com/genIoco/gcc-vxworks/assets/166282486/314cc080-fbe6-496f-855c-bafaf546b5d2)

**Comment by genIoco** [comment]
我也是虚拟机的vxworks，我用Workbench编译了相同的代码也是报相同的错误，目前我怀疑是vxworks kernel缺少部分c++的组件，感觉通过手动向vxworks kernel中添加相应的组件或许能够解决这个问题。

**Comment by yuzu-ogura** [comment]
> 是的成功了，生成后的文件类型vxworks的可执行文件，在vxworks中可使用`ld`命令加载程序，并运行`main`主函数，如下图 ![image](https://private-user-images.githubusercontent.com/49811656/320396508-db159193-e39f-4613-a01e-bc43a2004599.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NjU2ODUsIm5iZiI6MTcxMjU2NTM4NSwicGF0aCI6Ii80OTgxMTY1Ni8zMjAzOTY1MDgtZGIxNTkxOTMtZTM5Zi00NjEzLWEwMWUtYmM0M2EyMDA0NTk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDA4MzYyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiMmQyN2U0Yzk4M2Q2M2M1NmIzYWU5NmRmM2JmNGMyMDMzODEzYWI4MDMyNzk0OTYyNDJkZTg4OTc1Y2M0YWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EHKzGW1Oi-Aelf6R52Fb2-Zq-5sPAsss9S_U1Mntv1w)

那您这里加载为什么是成功的？另外，像您说的手动向vxworks kernel中添加组件要怎么操作呢？

**Comment by genIoco** [comment]
我的代码是纯C语言的代码，并不是c++的，添加组件需要用到Workbench编译vxworks系统，在Workbench里面有一个Kernel Configuration，里面配置项太多了。
PS:只是猜测不确定行不行，毕竟组件太多了
![image](https://github.com/genIoco/gcc-vxworks/assets/49811656/6ba91ffe-c72b-459a-8ebd-b08147f3b952)

**Comment by yuzu-ogura** [comment]
好的，原来是这样，非常感谢您的回答
